### ISSUE TITLE
RPM.Internal.Numbers - asWord8 is not used anywhere - remove ?

### ISSUE THREAD

**Issue by atodorov** [weldr/haskell-rpm#10]
The function asWord8 is not being used anywhere in the code.  @clumens do we want to remove it ?

**Comment by clumens** [comment]
It could be removed.  I've thought about it.  When I was writing this stuff it just seemed natural to have it in addition to asWord16, etc.  I thought it might be useful at some point, but I guess not.  It's not really much in the way of code though, which is why I haven't done anything yet.
